"""Add settings table

Revision ID: 0b3323df59c6
Revises: e9a689deaffb
Create Date: 2016-04-02 21:24:10.937991

"""

# revision identifiers, used by Alembic.
revision = '0b3323df59c6'
down_revision = 'e9a689deaffb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from shapr import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complexe_password', sa.Boolean(), nullable=False),
    sa.Column('password_len', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    bind = op.bulk_insert(table, [{'password_len':8, 'complexe_password': True}])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    ### end Alembic commands ###
