"""Add throttled column

Revision ID: 3ca1f04d32f1
Revises: dfcfbdc08051
Create Date: 2016-03-29 21:02:02.512533

"""

# revision identifiers, used by Alembic.
revision = '3ca1f04d32f1'
down_revision = 'dfcfbdc08051'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('throttled', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'throttled')
    ### end Alembic commands ###
