"""Add throttling settings

Revision ID: 8320f7e3adda
Revises: c1be93908088
Create Date: 2016-04-03 23:02:50.869797

"""

# revision identifiers, used by Alembic.
revision = '8320f7e3adda'
down_revision = 'c1be93908088'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('login_throttle_count', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('settings', sa.Column('login_throttle_period', sa.Integer(), nullable=False, server_default='30'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'login_throttle_period')
    op.drop_column('settings', 'login_throttle_count')
    ### end Alembic commands ###
