"""Add date field to event

Revision ID: 8b7bfbb170e1
Revises: c64accb3f416
Create Date: 2016-04-02 23:17:42.697525

"""

# revision identifiers, used by Alembic.
revision = '8b7bfbb170e1'
down_revision = 'c64accb3f416'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'date')
    ### end Alembic commands ###
