"""empty message

Revision ID: 8db7fcb53eef
Revises: 8320f7e3adda
Create Date: 2016-04-03 23:15:38.927168

"""

# revision identifiers, used by Alembic.
revision = '8db7fcb53eef'
down_revision = '8320f7e3adda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('password_expiry', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_password_set_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_set_at')
    op.drop_column('settings', 'password_expiry')
    ### end Alembic commands ###
