"""Create events table

Revision ID: c64accb3f416
Revises: c6c882e27d89
Create Date: 2016-04-02 23:14:13.427278

"""

# revision identifiers, used by Alembic.
revision = 'c64accb3f416'
down_revision = 'c6c882e27d89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    ### end Alembic commands ###
