"""Add password_reset field

Revision ID: e9a689deaffb
Revises: 3ca1f04d32f1
Create Date: 2016-03-29 21:51:39.880516

"""

# revision identifiers, used by Alembic.
revision = 'e9a689deaffb'
down_revision = '3ca1f04d32f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset', sa.Boolean(), nullable=False,
        server_default=sa.sql.expression.false()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset')
    ### end Alembic commands ###
